run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: false
  build-tags:
    - local
  skip-dirs:
    - generated
    - vendor
  skip-dirs-use-default: false
  skip-files:
    - .py$
    - .j2$
    - .yaml$
    - .yml$
  allow-parallel-runners: true
  allow-serial-runners: true
  max-issues-per-linter: 5
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ''
  sort-results: true
linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 200
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: ruler
  gomnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '8'
      - '10'
      - '16'
      - '32'
      - '64'
      - '255'
      - '1024'
      - '4096'
    ignored-functions:
      - strings.SplitN
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
    ignore-words:
      - mosquitto
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
