name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: 3.6.1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test-go
