name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.ref }}
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.ref }}
  build:
    needs: [lint, test]
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}
