name: Lint
on:
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout.When checking out the repository thattriggered a workflow, this defaults to the reference or SHA for that event.
        required: true
        default: ${{ github.ref }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Install protoc
        uses: arduino/setup-protoc@v1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache temporary
        uses: actions/cache@v3
        with:
          key: tmp-${{ runner.os }}-${{ hashFiles('Makefile.tools') }}
          path: .tmp
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          path: .venv
      - name: Lint Proto
        run: BUF_LINT_FORMAT="github-actions" make lint-proto
      - name: Lint Go
        run: GOLANGCI_LINT_FORMAT="github-actions" make lint-go
