name: Test
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The branch, tag or SHA to checkout.When checking out the repository thattriggered a workflow, this defaults to the reference or SHA for that event.
        required: true
        default: ${{ github.ref }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Install postgresql
        run: sudo apt-get install postgresql postgresql-contrib
      - name: Install protoc
        uses: arduino/setup-protoc@v1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Cache temporary
        uses: actions/cache@v3
        with:
          key: tmp-${{ runner.os }}-${{ hashFiles('Makefile.tools') }}
          path: .tmp
      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          path: .venv
      - name: Test Go
        run: make test-go
      - name: Test Py
        run: make test-python
